#ifndef CONFIG__H_
#define CONFIG__H_

#define LED_DISPLAY_ACTIVATED 1
#define UART_DISPLAY_ACTIVATED 0


#define LED_DISPLAY_PIN 27
#define LED_DISPLAY_LENGTH 14                     //14
#define LED_DISPLAY_HEIGHT 41                    //41
#define LED_DISPLAY_COUNT_LED LED_DISPLAY_LENGTH* LED_DISPLAY_HEIGHT  //574

#define LED_DISPLAY_OFFSET_BETWEEN_LINES 6
#define LED_DISPLAY_LINE_1 1 //temp ins
#define LED_DISPLAY_LINE_2 LED_DISPLAY_LINE_1+LED_DISPLAY_OFFSET_BETWEEN_LINES // humi ins
#define LED_DISPLAY_LINE_3 LED_DISPLAY_LINE_2+LED_DISPLAY_OFFSET_BETWEEN_LINES  //airr qual
#define LED_DISPLAY_LINE_4 LED_DISPLAY_LINE_3+LED_DISPLAY_OFFSET_BETWEEN_LINES  //time
#define LED_DISPLAY_LINE_5 LED_DISPLAY_LINE_4+LED_DISPLAY_OFFSET_BETWEEN_LINES //date
#define LED_DISPLAY_LINE_6 LED_DISPLAY_LINE_5+LED_DISPLAY_OFFSET_BETWEEN_LINES  //temp out
#define LED_DISPLAY_LINE_7 LED_DISPLAY_LINE_6+LED_DISPLAY_OFFSET_BETWEEN_LINES  //humi out


#define SDA_PIN_AHT10 33
#define SCL_PIN_AHT10 32

#define LIGHT_SENSOR_PIN A0

#define BUTTON_PIN   5

















































#endif /* CONFIG__H_ */